apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: retail-app
type: Opaque
stringData:
  mysql-host: "project-bedrock-mysql.c096iescirdl.us-east-1.rds.amazonaws.com"
  mysql-username: "admin"
  mysql-password: "Bedrock2025Secure"
  mysql-database: "retailstore"
  postgres-host: "project-bedrock-postgresql.c096iescirdl.us-east-1.rds.amazonaws.com"
  postgres-username: "dbadmin"
  postgres-password: "Bedrock2025Secure"
  postgres-database: "retailstore"
